import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Acme, Vollkorn, Lato } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./config.scss"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const myFont = Lato({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Authentication by Next.js",
  description: "Generated by Artin Mohajeri",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myFont.className}
      >
        <div className="container">

          {children}
        </div>
      </body>
    </html>
  );
}
